# Generated by Django 4.0 on 2021-12-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_question_answer_question_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='embedding',
            field=models.TextField(max_length=12000),
        ),
    ]
