# Generated by Django 4.0 on 2022-01-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_question_answer_question_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='embedding',
            field=models.TextField(max_length=12000),
        ),
    ]
