# Generated by Django 4.0 on 2022-01-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0003_question_subject_alter_question_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='embedding',
            field=models.BinaryField(),
        ),
    ]
