# Generated by Django 4.0 on 2022-01-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0004_alter_question_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='embedding',
            field=models.TextField(max_length=12000),
        ),
    ]
