# Generated by Django 4.1.4 on 2022-12-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0005_alter_question_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.TextField(blank=True, max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(max_length=12000),
        ),
    ]
