# Generated by Django 4.1.4 on 2022-12-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_account_password_alter_login_password"),
        ("examples", "0006_alter_question_answer_alter_question_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("map", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnswerDiagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base64string", models.TextField(blank=True, null=True)),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examples.answer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnswerText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examples.answer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.TextField()),
                ("year", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "postedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionDiagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base64string", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="question",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="question",
            name="embedding",
        ),
        migrations.RemoveField(
            model_name="question",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="question",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="question",
            name="text",
        ),
        migrations.RemoveField(
            model_name="question",
            name="year",
        ),
        migrations.AddField(
            model_name="question",
            name="map",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="text_embedding",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Diagram",
        ),
        migrations.AddField(
            model_name="questiontext",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="examples.question",
            ),
        ),
        migrations.AddField(
            model_name="questiondiagram",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="examples.question",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="examples.collection",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="examples.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="examples.collection",
            ),
        ),
    ]
