# Generated by Django 4.0 on 2022-01-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarizer',
            name='summary',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='summarizer',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
