# Generated by Django 4.0 on 2021-12-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_id', models.CharField(max_length=200)),
                ('isTaken', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiry_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_device_id', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=200)),
                ('amount_paid', models.DecimalField(decimal_places=3, max_digits=5)),
                ('date_of_payment', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiry_date', models.DateTimeField(null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accid', to='accounts.account')),
            ],
        ),
    ]
