# Generated by Django 4.0 on 2022-02-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_device_id',
            field=models.CharField(max_length=100),
        ),
    ]
