# Generated by Django 4.0 on 2021-12-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(max_length=25),
        ),
    ]
