# Generated by Django 4.0 on 2022-01-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='device_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
