# Generated by Django 4.0 on 2022-01-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='device_id',
            field=models.CharField(max_length=100),
        ),
    ]
