# Generated by Django 4.0 on 2022-01-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocr',
            name='base64string',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='ocr',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
